### ISSUE TITLE
figure out how we can use these hidden gems in Gemfile

### ISSUE THREAD

**Issue by rdcsg** [CraftAcademy/slow_food_june#10]
WE have a lot of gems that are commented out. 
- Why are they commented out? 
- What are these gems used for? 
- Are we going to need any of these?
# gem 'dm-core', '1.2.1'
# gem 'dm-sqlite-adapter', '1.2.0'
# gem 'dm-migrations', '1.2.0'
# gem 'dm-serializer', '1.2.2'
# gem 'dm-timestamps', '1.2.0'
# gem 'dm-transactions', '1.2.0'
# gem 'dm-types', '1.2.2'
# gem 'dm-validations', '1.2.0'

**Comment by rdcsg** [comment]
@MikaelFeher you closed this. Did you reach any conclusion to this?

**Comment by MikaelFeher** [comment]
they were already included with another gem: "gem 'data_mapper'"...
