### ISSUE TITLE
find out the problem with the db err in install

### ISSUE THREAD

**Issue by rdcsg** [CraftAcademy/slow_food_june#2]

**Comment by lollypop27** [comment]
this maybe a solution:
http://stackoverflow.com/questions/31123729/an-error-occurred-while-installing-pg-0-18-2-and-bundler-cannot-continue

**Comment by tochman** [comment]
Please attach the error message (formatted as code) to this issue.

**Comment by MikaelFeher** [comment]
Error message:

```
An error occurred while installing pg (0.18.4), and Bundler cannot continue.
Make sure that `gem install pg -v '0.18.4'` succeeds before bundling.
```

Solution:

```
brew install postgres
```

```
brew install qt
```

And then run:

```
bundle install
```

the first one solves dependency-issues with the `pg` gem and the second one solves dependency-issues
with the `capybara web-kit`.
