### ISSUE TITLE
Order system

### ISSUE THREAD

**Issue by tochman** [CraftAcademy/slow_food_june#34]
```
As a visitor
  In order to add a dish to my order when I click on 'Add to order' for a specific dish
  I would like to see an 'Add to order' link on every dish
```

**Comment by tochman** [comment]
1. Show 'Add to order' link in Dish listing
2. Create  controller action (route) to create an order and to add the dish as an order item
3. Add new models - Order and OrderItem with one to meny relationship
4. Add relationship User has many Order
5. And Order should have a status (Active or Closed, active: true/false)

**Comment by MikaelFeher** [comment]
pull request created.
https://github.com/CraftAcademy/slow_food_june/pull/36
